---
title: "Indian Premier League (IPL) data analysis"
subtitle: 'STAT585 Final Project Report'
date: "`r format(Sys.time(), '%d %B %Y')`"
author: "Ashish Jain"
output: pdf_document
---

\section{Abstract}
Cricket is one of the most popular and played sports in India. There are three standard types of cricket matches, Five-day match (Test Match), 50 overs match (One day match), and Twenty overs match (T20). Although all formats are quite popular but during the last decade, the popularity of the T20 matches has increased exponentially. The main reason for the popularity of T20 matches is more action in short time. The introduction of various T20 tournaments has also added to its popularity. Indian Premier League (IPL) is the biggest event among all the T20 tournaments across the globe. It is an annual tournament and consists of two stages. In the first or the league stage, each team plays against the other team twice. In the second stage, the top four teams after the league stage compete for the title. We are going to use the IPL data from the year 2008 to 2016. The raw data is available at [Cricsheet website](http://cricsheet.org/downloads/). The raw data consists ball by ball details individually for every match (577 files). The processed data has been downloaded from [Kaggle](https://www.kaggle.com/manasgarg/ipl). For carrying out the analysis we have divided this project into two parts. In the first part, we will further process the data so that it can be used for the next part (visualization and analysis). In the next part, we will develop a shiny application in which the data can be analyzed by plotting and changing various parameters including year, team, and player.

The GitHub repository which I am using for this project is https://github.com/ashishjain1988/STAT585-FinalProject

\section{Introduction}

\section{Dataset}
As mentioned earlier, the IPL dataset has been available at [Cricsheet website](http://cricsheet.org/downloads/). The raw data consists ball by ball details (including bowler, batsmen, run scored, match, and teams.) individually for every match (577 files). These files also consists the meta information about the match including the the venue, toss winner, match winner, stadium and city. Our aim was first to process the data and make it tidy but this step has already done previously. For our project, we downloaded and used the processed data from [Kaggle](https://www.kaggle.com/manasgarg/ipl). The processed data consists of two files. The first file, `matches.csv` consists of meta-information about all the matches as described earlier as a comma seperated file. The second file, `deliveries.csv` consists of the ball by ball information of the matches. These files have a common identifier called as "match_id" which is the linking key for these two files.
```
library(tidyr)
library(plotly)
library(ggmap)
library(rworldmap)
matches <- read.csv("../data/matches.csv", stringsAsFactors = FALSE)
ballbyball <- read.csv("../data/deliveries1.csv", stringsAsFactors = FALSE)
```

\section{Methods}

\subsection{Processing of the dataset}
Although, we downloaded the processed data from [Kaggle](https://www.kaggle.com/manasgarg/ipl), there is still processing we need to do before using the dataset. In our analysis, we want to point each venue of the matches on a world map with the number of matches for a particular team. For this visualization, we need to extract the longitude and latitude for the venues. For this, we used the `ggmap` and `rworldmap` to extract the details. In total, the matches was hosted by 30 different venues across all seasons. By using `ggmap` we extracted the location information and stored in the `location_mapping.csv` file which is under the data folder.

```
cities<-unlist(matches %>% distinct(city) %>% filter(city != ""))
points<-geocode(cities)
row.names(points)<-cities
points<-points[,2:3]
coord2loc <- function(points)
{
  countriesSP <- getMap(resolution='low')
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  
  indices = over(pointsSP, countriesSP)
  #indices$continent   # returns the continent (6 continent model)
  #indices$REGION   # returns the continent (7 continent model)
  indices$ADMIN  #returns country name
  #indices$ISO3 # returns the ISO3 code 
}
countries<-coord2loc(as.matrix(points))
points[,3]<-countries
points["Kochi",]$V3<-"India"
write.csv(points,"../data/location_mapping.csv")
#map <- get_map(location = 'India', zoom = 4)
#ggmap(map) + geom_point(aes(x=77.10249,y=28.70406,label="Delhi"))
#mapWorld <- borders("world", colour="gray50", fill="gray50")
#mp <- ggplot() +   mapWorld
#mp <- mp+ geom_point(aes(x=visit.x, y=visit.y) ,color="blue", size=3)
```

\section{Results}
In this section, we will discuss about different features of the developed shiny application and its interactivity. The shiny application has three different tabs which is based on the visulization of data based on IPL season, Team, and Player.

\subsection{IPL seasons analysis}
In this section, the user can visualize and analyze the data grouped together by the season. The user can use various plots which are described below for a specific season by selecting the season in the select widget. In addition to that, the user can also filter the teams or players by selecting the minimum number of seasons played through the sliderbar. Now we talk about the different plots that are there in the shiny application.

\subsubsection{Toss Winner}
This plot compares the count of toss and match winner across different teams in a season. The information is displayed as a histogram. This plot can be used to see the effect of winning the toss on the match result for teams. The user can also hovers over the bars and get the details. For example,<One plot for this>

\subsubsection{Comparison of total matches played and won}
This plot compares the total matchs played and total match won across different teams in a season. The information is displayed as a histogram. This plot can be used to check the performace of the teams in a season. This will also tells us the winner of a particular season. The user can also hovers over the bars and get the details. For example,<One plot for this>

\subsubsection{Comparison of average runs scored by teams}
This plot compares the average runs scored across different teams in a season. The information is displayed as a boxplot. This plot can be used to check the performace of the teams in a season by displaying their batting performance of the teams in a season. The user can also hovers over the bars and get the details about the mean, outlier scores, upper and lower quartile. For example,<One plot for this>

\subsubsection{Top batsmen}
This plot compares the total runs scored by batsmen in a season. The information is displayed as a histogram. This plot shows the top 10 batsmen in a season based on the number of runs scored. The number of runs scored by the batsmen are displayed above the plot. For example,<One plot for this>

\subsubsection{Top Bowler}
This plot compares the total runs scored by batsmen in a season. The information is displayed as a histogram. This plot shows the top 10 batsmen in a season based on the number of runs scored. The number of runs scored by the batsmen are displayed above the plot. For example,<One plot for this>

\subsection{Team performance Analysis}
In this section, the user can visualize and analyze the data grouped together for a team across all seasons. The user can use various plots which are described below for a team by selecting the team in the select widget. In addition to that, the user can also filter the teams by selecting the minimum number of seasons played through the sliderbar (Automatic updation of team select widget). Now we talk about the different plots that are there for this.

\subsubsection{Comparison of total matches played and won}
This plot compares the total matchs played and total match won by a team across the seasons. The information is displayed as a histogram. This plot can be used to check the performace of a team across different seasons. The user can also hovers over the bars and get the details. For example,<One plot for this>

\subsubsection{Comparison of average runs scored}
This plot compares the average runs scored by a team across the seasons. The information is displayed as a boxplot. This plot can be used to check the performace of a team by checking their batting performance across the seasons. The user can also hovers over the bars and get the details about the mean, outlier scores, upper and lower quartile. For example,<One plot for this>

\subsubsection{Venue Details}

\subsection{Player's performance analysis}
In this section, the user can visualize and analyze the data grouped for a player across all seasons. The user can use various plots which are described below for a player to analyze his performace by selecting the player in the select widget. In addition to that, the user can also filter the players by selecting the minimum number of seasons played through the sliderbar (Automatic updation of player select widget).

\subsubsection{Player of match awards}
\subsubsection{Average runs scored across seasons}
\subsubsection{Total Wickets}

\section{Discussion}

\section{Future Work}
